"""
GUARDEN — TFLite INT8 Quantization
Converts trained .h5 model to INT8 .tflite for ESP32-C3 deployment.

Usage:
    python3 model/quantize.py --model model/guarden_v1.h5 --dataset /path/to/dataset
"""

import argparse
import glob
import os

import numpy as np
import tensorflow as tf


IMG_SIZE = 96


def representative_dataset(dataset_path: str):
    """Yields calibration samples for INT8 quantization (100 images)."""
    image_paths = glob.glob(os.path.join(dataset_path, "**", "*.jpg"), recursive=True)
    image_paths += glob.glob(os.path.join(dataset_path, "**", "*.png"), recursive=True)
    np.random.shuffle(image_paths)

    for path in image_paths[:100]:
        img = tf.keras.preprocessing.image.load_img(
            path, target_size=(IMG_SIZE, IMG_SIZE), color_mode="grayscale"
        )
        arr = tf.keras.preprocessing.image.img_to_array(img)
        arr = arr / 255.0
        arr = np.expand_dims(arr, axis=0).astype(np.float32)
        yield [arr]


def quantize(model_path: str, dataset_path: str, output_dir: str) -> str:
    os.makedirs(output_dir, exist_ok=True)
    tflite_path = os.path.join(output_dir, "guarden_v1_int8.tflite")

    print(f"Loading model: {model_path}")
    model = tf.keras.models.load_model(model_path)

    converter = tf.lite.TFLiteConverter.from_keras_model(model)

    # Full INT8 quantization
    converter.optimizations = [tf.lite.Optimize.DEFAULT]
    converter.representative_dataset = lambda: representative_dataset(dataset_path)
    converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
    converter.inference_input_type  = tf.int8
    converter.inference_output_type = tf.int8

    print("Quantizing to INT8...")
    tflite_model = converter.convert()

    with open(tflite_path, "wb") as f:
        f.write(tflite_model)

    size_kb = len(tflite_model) / 1024
    print(f"\n✓ TFLite model saved: {tflite_path}")
    print(f"  Size: {size_kb:.1f} KB")

    if size_kb > 300:
        print("⚠ Warning: Model > 300KB — may not fit in ESP32-C3 flash with other firmware")

    # Also generate C header for embedding in firmware
    header_path = os.path.join("edge", "src", "model_data.h")
    print(f"\nGenerating C header: {header_path}")
    _generate_c_header(tflite_model, header_path)

    return tflite_path


def _generate_c_header(model_data: bytes, output_path: str) -> None:
    """Converts .tflite bytes to a C header array (same as xxd -i)."""
    os.makedirs(os.path.dirname(output_path), exist_ok=True)

    hex_data = ", ".join(f"0x{b:02x}" for b in model_data)
    c_code = f"""// Auto-generated by model/quantize.py — DO NOT EDIT
// GUARDEN TFLite INT8 Model

#pragma once
#include <stdint.h>

const unsigned char g_model_data[] = {{
    {hex_data}
}};
const unsigned int g_model_data_len = {len(model_data)};
"""

    with open(output_path, "w") as f:
        f.write(c_code)

    print(f"✓ C header written: {output_path} ({len(model_data)} bytes)")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Quantize GUARDEN model to INT8 TFLite")
    parser.add_argument("--model",   required=True, help="Path to .h5 model")
    parser.add_argument("--dataset", required=True, help="Path to dataset for calibration")
    parser.add_argument("--output",  default="model/")
    args = parser.parse_args()

    quantize(args.model, args.dataset, args.output)
